import sqlite3 from 'sqlite3';
import dotenv from 'dotenv';
import { initializeDatabase } from '../database/schema.js';

dotenv.config();

const DB_PATH = process.env.DATABASE_PATH || './data/ppp_converter.db';
const db = new sqlite3.Database(DB_PATH);
db.serialize();
initializeDatabase(db);

const MVP_COUNTRY_CODES = new Set(['IN', 'US', 'GB', 'JP', 'AU', 'CA', 'DE', 'FR', 'SG', 'BR']);
const MVP_ITEM_NAMES = new Set([
  'Breakfast pastry or snack (1 item)',
  'Casual sit-down meal (1 person)',
  'Fast food combo meal (1 person)',
  'Bottled water (1.5L)',
  'Coffee or tea (1 cup)',
  'Basic groceries (1 week, 1 person)',
  'Public transit (1 ride)',
  'Taxi or rideshare (short ride, ~3km)',
  'Local SIM card (one-time, no data)',
  'Budget hotel or guesthouse room (1 night)'
]);

function runAsync(sql, params=[]) {
  return new Promise((resolve, reject) => {
    db.run(sql, params, function(err) {
      if (err) reject(err);
      else resolve(this);
    });
  });
}

function getAsync(sql, params=[]) {
  return new Promise((resolve, reject) => {
    db.get(sql, params, (err, row) => {
      if (err) reject(err);
      else resolve(row);
    });
  });
}

async function seed() {
  try {
    console.log('Seeding database at', DB_PATH);

    await runAsync(`DELETE FROM prices`);
    await runAsync(`DELETE FROM items`);
    await runAsync(`DELETE FROM countries`);

    // Countries: real PPP conversion factors and official exchange rates
    // from the World Bank (most recent available year per country, ~2023),
    // joined with ISO currency codes. ppp_index = local currency per
    // international $ (PPP); exchange_rate = local currency per USD (market).
    const countries = [
      { code: 'AF', name: 'Afghanistan', currency: 'AFN', symbol: '؋', ppp: 14.8009, exch: 76.8135, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'AL', name: 'Albania', currency: 'ALL', symbol: 'L', ppp: 39.4549, exch: 100.645, region: 'Europe & Central Asia' },
      { code: 'DZ', name: 'Algeria', currency: 'DZD', symbol: 'د.ج', ppp: 43.3619, exch: 135.8429, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'AD', name: 'Andorra', currency: 'EUR', symbol: '€', ppp: 0.6036, exch: 0.9247, region: 'Europe & Central Asia' },
      { code: 'AO', name: 'Angola', currency: 'AOA', symbol: 'Kz', ppp: 218.5066, exch: 685.0202, region: 'Sub-Saharan Africa' },
      { code: 'AG', name: 'Antigua and Barbuda', currency: 'XCD', symbol: '$', ppp: 1.8365, exch: 2.7, region: 'Latin America & Caribbean' },
      { code: 'AR', name: 'Argentina', currency: 'ARS', symbol: '$', ppp: 139.8073, exch: 296.258, region: 'Latin America & Caribbean' },
      { code: 'AM', name: 'Armenia', currency: 'AMD', symbol: '֏', ppp: 148.7078, exch: 392.4763, region: 'Europe & Central Asia' },
      { code: 'AW', name: 'Aruba', currency: 'AWG', symbol: 'ƒ', ppp: 1.3728, exch: 1.79, region: 'Latin America & Caribbean' },
      { code: 'AU', name: 'Australia', currency: 'AUD', symbol: 'A$', ppp: 1.3375, exch: 1.5052, region: 'East Asia & Pacific' },
      { code: 'AT', name: 'Austria', currency: 'EUR', symbol: '€', ppp: 0.7046, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'AZ', name: 'Azerbaijan', currency: 'AZN', symbol: '₼', ppp: 0.5127, exch: 1.7, region: 'Europe & Central Asia' },
      { code: 'BS', name: 'Bahamas', currency: 'BSD', symbol: '$', ppp: 0.978, exch: 1, region: 'Latin America & Caribbean' },
      { code: 'BH', name: 'Bahrain', currency: 'BHD', symbol: '.د.ب', ppp: 0.1716, exch: 0.376, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'BD', name: 'Bangladesh', currency: 'BDT', symbol: '৳', ppp: 28.6307, exch: 106.3095, region: 'South Asia' },
      { code: 'BB', name: 'Barbados', currency: 'BBD', symbol: '$', ppp: 2.1626, exch: 2, region: 'Latin America & Caribbean' },
      { code: 'BY', name: 'Belarus', currency: 'BYN', symbol: 'Br', ppp: 0.7702, exch: 3.0074, region: 'Europe & Central Asia' },
      { code: 'BE', name: 'Belgium', currency: 'EUR', symbol: '€', ppp: 0.7035, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'BZ', name: 'Belize', currency: 'BZD', symbol: 'BZ$', ppp: 1.0815, exch: 2, region: 'Latin America & Caribbean' },
      { code: 'BJ', name: 'Benin', currency: 'XOF', symbol: 'CFA', ppp: 204.7922, exch: 606.655, region: 'Sub-Saharan Africa' },
      { code: 'BM', name: 'Bermuda', currency: 'BMD', symbol: '$', ppp: 1.1594, exch: 1, region: 'North America' },
      { code: 'BT', name: 'Bhutan', currency: 'BTN', symbol: 'BTN', ppp: 19.5166, exch: 82.5993, region: 'South Asia' },
      { code: 'BO', name: 'Bolivia', currency: 'BOB', symbol: 'Bs.', ppp: 2.2912, exch: 6.91, region: 'Latin America & Caribbean' },
      { code: 'BA', name: 'Bosnia and Herzegovina', currency: 'BAM', symbol: 'KM', ppp: 0.6705, exch: 1.8092, region: 'Europe & Central Asia' },
      { code: 'BW', name: 'Botswana', currency: 'BWP', symbol: 'P', ppp: 5.0642, exch: 13.5964, region: 'Sub-Saharan Africa' },
      { code: 'BR', name: 'Brazil', currency: 'BRL', symbol: 'R$', ppp: 2.4476, exch: 4.9944, region: 'Latin America & Caribbean' },
      { code: 'BN', name: 'Brunei', currency: 'BND', symbol: 'B$', ppp: 0.5195, exch: 1.3431, region: 'East Asia & Pacific' },
      { code: 'BG', name: 'Bulgaria', currency: 'BGN', symbol: 'лв', ppp: 0.7386, exch: 1.809, region: 'Europe & Central Asia' },
      { code: 'BF', name: 'Burkina Faso', currency: 'XOF', symbol: 'CFA', ppp: 192.0153, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'BI', name: 'Burundi', currency: 'BIF', symbol: 'FBu', ppp: 751.9382, exch: 2574.0517, region: 'Sub-Saharan Africa' },
      { code: 'CV', name: 'Cabo Verde', currency: 'CVE', symbol: '$', ppp: 47.6603, exch: 101.8048, region: 'Sub-Saharan Africa' },
      { code: 'KH', name: 'Cambodia', currency: 'KHR', symbol: '៛', ppp: 1344.1279, exch: 4110.6527, region: 'East Asia & Pacific' },
      { code: 'CM', name: 'Cameroon', currency: 'XAF', symbol: 'FCFA', ppp: 192.8724, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'CA', name: 'Canada', currency: 'CAD', symbol: 'C$', ppp: 1.1397, exch: 1.3499, region: 'North America' },
      { code: 'KY', name: 'Cayman Islands', currency: 'KYD', symbol: '$', ppp: 0.9343, exch: 0.8333, region: 'Latin America & Caribbean' },
      { code: 'CF', name: 'Central African Republic', currency: 'XAF', symbol: 'FCFA', ppp: 239.3184, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'TD', name: 'Chad', currency: 'XAF', symbol: 'FCFA', ppp: 213.2445, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'CL', name: 'Chile', currency: 'CLP', symbol: '$', ppp: 432.5621, exch: 840.0665, region: 'Latin America & Caribbean' },
      { code: 'CN', name: 'China', currency: 'CNY', symbol: '¥', ppp: 3.6437, exch: 7.084, region: 'East Asia & Pacific' },
      { code: 'CO', name: 'Colombia', currency: 'COP', symbol: '$', ppp: 1425.4339, exch: 4325.955, region: 'Latin America & Caribbean' },
      { code: 'KM', name: 'Comoros', currency: 'KMF', symbol: 'CF', ppp: 186.2476, exch: 454.9912, region: 'Sub-Saharan Africa' },
      { code: 'CG', name: 'Congo', currency: 'XAF', symbol: 'FCFA', ppp: 219.4169, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'CR', name: 'Costa Rica', currency: 'CRC', symbol: '₡', ppp: 318.8418, exch: 544.0508, region: 'Latin America & Caribbean' },
      { code: 'CI', name: 'Cote d\'Ivoire', currency: 'XOF', symbol: 'CFA', ppp: 217.2404, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'HR', name: 'Croatia', currency: 'EUR', symbol: '€', ppp: 0.4296, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'CW', name: 'Curacao', currency: 'ANG', symbol: 'ƒ', ppp: 1.2391, exch: 1.79, region: 'Latin America & Caribbean' },
      { code: 'CY', name: 'Cyprus', currency: 'EUR', symbol: '€', ppp: 0.5657, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'CZ', name: 'Czech Republic', currency: 'CZK', symbol: 'Kč', ppp: 12.5761, exch: 22.1981, region: 'Europe & Central Asia' },
      { code: 'CD', name: 'DR Congo', currency: 'CDF', symbol: 'FC', ppp: 932.4305, exch: 2340.0357, region: 'Sub-Saharan Africa' },
      { code: 'DK', name: 'Denmark', currency: 'DKK', symbol: 'kr', ppp: 6.0549, exch: 6.8897, region: 'Europe & Central Asia' },
      { code: 'DJ', name: 'Djibouti', currency: 'DJF', symbol: 'Fdj', ppp: 83.1637, exch: 177.721, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'DM', name: 'Dominica', currency: 'XCD', symbol: '$', ppp: 1.3194, exch: 2.7, region: 'Latin America & Caribbean' },
      { code: 'DO', name: 'Dominican Republic', currency: 'DOP', symbol: 'RD$', ppp: 23.103, exch: 56.1576, region: 'Latin America & Caribbean' },
      { code: 'EC', name: 'Ecuador', currency: 'USD', symbol: '$', ppp: 0.4233, exch: 1, region: 'Latin America & Caribbean' },
      { code: 'EG', name: 'Egypt', currency: 'EGP', symbol: 'E£', ppp: 4.7863, exch: 30.6264, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'SV', name: 'El Salvador', currency: 'USD', symbol: '$', ppp: 0.4232, exch: 1, region: 'Latin America & Caribbean' },
      { code: 'GQ', name: 'Equatorial Guinea', currency: 'XAF', symbol: 'FCFA', ppp: 232.6363, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'ER', name: 'Eritrea', currency: 'ERN', symbol: 'Nfk', ppp: 4.9385, exch: 15.075, region: 'Sub-Saharan Africa' },
      { code: 'EE', name: 'Estonia', currency: 'EUR', symbol: '€', ppp: 0.573, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'SZ', name: 'Eswatini', currency: 'SZL', symbol: 'L', ppp: 6.1331, exch: 18.4536, region: 'Sub-Saharan Africa' },
      { code: 'ET', name: 'Ethiopia', currency: 'ETB', symbol: 'Br', ppp: 22.1448, exch: 54.6009, region: 'Sub-Saharan Africa' },
      { code: 'FO', name: 'Faroe Islands', currency: 'DKK', symbol: 'kr', ppp: 6.2647, exch: 6.8897, region: 'Europe & Central Asia' },
      { code: 'FJ', name: 'Fiji', currency: 'FJD', symbol: 'FJ$', ppp: 0.9106, exch: 2.2501, region: 'East Asia & Pacific' },
      { code: 'FI', name: 'Finland', currency: 'EUR', symbol: '€', ppp: 0.7703, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'FR', name: 'France', currency: 'EUR', symbol: '€', ppp: 0.6785, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'GA', name: 'Gabon', currency: 'XAF', symbol: 'FCFA', ppp: 228.0321, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'GM', name: 'Gambia', currency: 'GMD', symbol: 'D', ppp: 16.4369, exch: 61.0963, region: 'Sub-Saharan Africa' },
      { code: 'GE', name: 'Georgia', currency: 'GEL', symbol: '₾', ppp: 0.8683, exch: 2.628, region: 'Europe & Central Asia' },
      { code: 'DE', name: 'Germany', currency: 'EUR', symbol: '€', ppp: 0.7011, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'GH', name: 'Ghana', currency: 'GHS', symbol: '₵', ppp: 3.4771, exch: 11.0204, region: 'Sub-Saharan Africa' },
      { code: 'GR', name: 'Greece', currency: 'EUR', symbol: '€', ppp: 0.5066, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'GL', name: 'Greenland', currency: 'DKK', symbol: 'kr', ppp: 5.1121, exch: 6.8897, region: 'Europe & Central Asia' },
      { code: 'GD', name: 'Grenada', currency: 'XCD', symbol: '$', ppp: 1.6246, exch: 2.7, region: 'Latin America & Caribbean' },
      { code: 'GT', name: 'Guatemala', currency: 'GTQ', symbol: 'Q', ppp: 3.281, exch: 7.832, region: 'Latin America & Caribbean' },
      { code: 'GN', name: 'Guinea', currency: 'GNF', symbol: 'FG', ppp: 3054.6991, exch: 9565.0822, region: 'Sub-Saharan Africa' },
      { code: 'GW', name: 'Guinea-Bissau', currency: 'XOF', symbol: 'CFA', ppp: 200.4715, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'GY', name: 'Guyana', currency: 'GYD', symbol: '$', ppp: 77.9982, exch: 208.5, region: 'Latin America & Caribbean' },
      { code: 'HT', name: 'Haiti', currency: 'HTG', symbol: 'G', ppp: 73.0494, exch: 141.0359, region: 'Latin America & Caribbean' },
      { code: 'HN', name: 'Honduras', currency: 'HNL', symbol: 'L', ppp: 11.0612, exch: 24.6016, region: 'Latin America & Caribbean' },
      { code: 'HK', name: 'Hong Kong', currency: 'HKD', symbol: 'HK$', ppp: 5.5359, exch: 7.8296, region: 'East Asia & Pacific' },
      { code: 'HU', name: 'Hungary', currency: 'HUF', symbol: 'Ft', ppp: 169.0871, exch: 353.0883, region: 'Europe & Central Asia' },
      { code: 'IS', name: 'Iceland', currency: 'ISK', symbol: 'kr', ppp: 137.8503, exch: 137.943, region: 'Europe & Central Asia' },
      { code: 'IN', name: 'India', currency: 'INR', symbol: '₹', ppp: 20.2904, exch: 82.5993, region: 'South Asia' },
      { code: 'ID', name: 'Indonesia', currency: 'IDR', symbol: 'Rp', ppp: 4819.7422, exch: 15236.8847, region: 'East Asia & Pacific' },
      { code: 'IR', name: 'Iran', currency: 'IRR', symbol: 'IRR', ppp: 94357.9751, exch: 42000, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'IQ', name: 'Iraq', currency: 'IQD', symbol: 'ع.د', ppp: 535.6667, exch: 1312.5, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'IE', name: 'Ireland', currency: 'EUR', symbol: '€', ppp: 0.7403, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'IL', name: 'Israel', currency: 'ILS', symbol: '₪', ppp: 3.4568, exch: 3.6674, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'IT', name: 'Italy', currency: 'EUR', symbol: '€', ppp: 0.6019, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'JM', name: 'Jamaica', currency: 'JMD', symbol: 'J$', ppp: 91.9086, exch: 154.1588, region: 'Latin America & Caribbean' },
      { code: 'JP', name: 'Japan', currency: 'JPY', symbol: '¥', ppp: 93.8317, exch: 140.4911, region: 'East Asia & Pacific' },
      { code: 'JO', name: 'Jordan', currency: 'JOD', symbol: 'د.ا', ppp: 0.3045, exch: 0.71, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'KZ', name: 'Kazakhstan', currency: 'KZT', symbol: '₸', ppp: 152.541, exch: 456.165, region: 'Europe & Central Asia' },
      { code: 'KE', name: 'Kenya', currency: 'KES', symbol: 'KSh', ppp: 43.0049, exch: 139.8464, region: 'Sub-Saharan Africa' },
      { code: 'KI', name: 'Kiribati', currency: 'AUD', symbol: 'A$', ppp: 0.9404, exch: 1.5052, region: 'East Asia & Pacific' },
      { code: 'XK', name: 'Kosovo', currency: 'EUR', symbol: '€', ppp: 0.364, exch: 0.9247, region: 'Europe & Central Asia' },
      { code: 'KW', name: 'Kuwait', currency: 'KWD', symbol: 'د.ك', ppp: 0.1974, exch: 0.3072, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'KG', name: 'Kyrgyzstan', currency: 'KGS', symbol: 'KGS', ppp: 25.7404, exch: 87.8561, region: 'Europe & Central Asia' },
      { code: 'LA', name: 'Laos', currency: 'LAK', symbol: '₭', ppp: 3934.8736, exch: 17688.8736, region: 'East Asia & Pacific' },
      { code: 'LV', name: 'Latvia', currency: 'EUR', symbol: '€', ppp: 0.4909, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'LB', name: 'Lebanon', currency: 'LBP', symbol: 'ل.ل', ppp: 23736.7904, exch: 13875.625, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'LS', name: 'Lesotho', currency: 'LSL', symbol: 'L', ppp: 5.868, exch: 18.4502, region: 'Sub-Saharan Africa' },
      { code: 'LR', name: 'Liberia', currency: 'LRD', symbol: '$', ppp: 0.4453, exch: 174.956, region: 'Sub-Saharan Africa' },
      { code: 'LY', name: 'Libya', currency: 'LYD', symbol: 'ل.د', ppp: 2.0947, exch: 4.8129, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'LT', name: 'Lithuania', currency: 'EUR', symbol: '€', ppp: 0.4909, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'LU', name: 'Luxembourg', currency: 'EUR', symbol: '€', ppp: 0.8075, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'MO', name: 'Macau', currency: 'MOP', symbol: 'MOP$', ppp: 4.6591, exch: 8.0634, region: 'East Asia & Pacific' },
      { code: 'MG', name: 'Madagascar', currency: 'MGA', symbol: 'Ar', ppp: 1246.0457, exch: 4429.5792, region: 'Sub-Saharan Africa' },
      { code: 'MW', name: 'Malawi', currency: 'MWK', symbol: 'MK', ppp: 401.6587, exch: 1161.0944, region: 'Sub-Saharan Africa' },
      { code: 'MY', name: 'Malaysia', currency: 'MYR', symbol: 'RM', ppp: 1.424, exch: 4.5606, region: 'East Asia & Pacific' },
      { code: 'MV', name: 'Maldives', currency: 'MVR', symbol: 'MVR', ppp: 7.8141, exch: 15.3868, region: 'South Asia' },
      { code: 'ML', name: 'Mali', currency: 'XOF', symbol: 'CFA', ppp: 199.466, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'MT', name: 'Malta', currency: 'EUR', symbol: '€', ppp: 0.5642, exch: 0.9248, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'MH', name: 'Marshall Islands', currency: 'USD', symbol: '$', ppp: 0.8999, exch: 1, region: 'East Asia & Pacific' },
      { code: 'MR', name: 'Mauritania', currency: 'MRU', symbol: 'UM', ppp: 11.1878, exch: 36.4892, region: 'Sub-Saharan Africa' },
      { code: 'MU', name: 'Mauritius', currency: 'MUR', symbol: '₨', ppp: 17.258, exch: 45.2672, region: 'Sub-Saharan Africa' },
      { code: 'MX', name: 'Mexico', currency: 'MXN', symbol: '$', ppp: 9.7513, exch: 17.7587, region: 'Latin America & Caribbean' },
      { code: 'FM', name: 'Micronesia', currency: 'USD', symbol: '$', ppp: 0.9258, exch: 1, region: 'East Asia & Pacific' },
      { code: 'MD', name: 'Moldova', currency: 'MDL', symbol: 'L', ppp: 6.9594, exch: 18.1639, region: 'Europe & Central Asia' },
      { code: 'MN', name: 'Mongolia', currency: 'MNT', symbol: '₮', ppp: 1123.8725, exch: 3465.7365, region: 'East Asia & Pacific' },
      { code: 'ME', name: 'Montenegro', currency: 'EUR', symbol: '€', ppp: 0.3558, exch: 0.9247, region: 'Europe & Central Asia' },
      { code: 'MA', name: 'Morocco', currency: 'MAD', symbol: 'ح.ج.', ppp: 3.9055, exch: 10.1314, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'MZ', name: 'Mozambique', currency: 'MZN', symbol: 'MT', ppp: 23.6757, exch: 63.8858, region: 'Sub-Saharan Africa' },
      { code: 'MM', name: 'Myanmar', currency: 'MMK', symbol: 'K', ppp: 435.0004, exch: 1381.6192, region: 'East Asia & Pacific' },
      { code: 'NA', name: 'Namibia', currency: 'NAD', symbol: '$', ppp: 6.8655, exch: 18.4463, region: 'Sub-Saharan Africa' },
      { code: 'NR', name: 'Nauru', currency: 'AUD', symbol: 'A$', ppp: 1.3798, exch: 1.5052, region: 'East Asia & Pacific' },
      { code: 'NP', name: 'Nepal', currency: 'NPR', symbol: 'रू', ppp: 33.5, exch: 132.1155, region: 'South Asia' },
      { code: 'NL', name: 'Netherlands', currency: 'EUR', symbol: '€', ppp: 0.7307, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'NZ', name: 'New Zealand', currency: 'NZD', symbol: 'NZ$', ppp: 1.4611, exch: 1.6284, region: 'East Asia & Pacific' },
      { code: 'NI', name: 'Nicaragua', currency: 'NIO', symbol: 'C$', ppp: 11.4293, exch: 36.4412, region: 'Latin America & Caribbean' },
      { code: 'NE', name: 'Niger', currency: 'XOF', symbol: 'CFA', ppp: 206.4873, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'NG', name: 'Nigeria', currency: 'NGN', symbol: '₦', ppp: 158.2924, exch: 645.1941, region: 'Sub-Saharan Africa' },
      { code: 'MK', name: 'North Macedonia', currency: 'MKD', symbol: 'ден', ppp: 19.4833, exch: 56.9472, region: 'Europe & Central Asia' },
      { code: 'NO', name: 'Norway', currency: 'NOK', symbol: 'kr', ppp: 8.9182, exch: 10.5633, region: 'Europe & Central Asia' },
      { code: 'OM', name: 'Oman', currency: 'OMR', symbol: '﷼', ppp: 0.1928, exch: 0.3845, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'PK', name: 'Pakistan', currency: 'PKR', symbol: '₨', ppp: 56.1985, exch: 280.3561, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'PW', name: 'Palau', currency: 'USD', symbol: '$', ppp: 0.8563, exch: 1, region: 'East Asia & Pacific' },
      { code: 'PA', name: 'Panama', currency: 'PAB', symbol: 'B/.', ppp: 0.4721, exch: 1, region: 'Latin America & Caribbean' },
      { code: 'PG', name: 'Papua New Guinea', currency: 'PGK', symbol: 'K', ppp: 2.2809, exch: 3.5896, region: 'East Asia & Pacific' },
      { code: 'PY', name: 'Paraguay', currency: 'PYG', symbol: '₲', ppp: 2614.3554, exch: 7288.8721, region: 'Latin America & Caribbean' },
      { code: 'PE', name: 'Peru', currency: 'PEN', symbol: 'S/', ppp: 1.7359, exch: 3.7438, region: 'Latin America & Caribbean' },
      { code: 'PH', name: 'Philippines', currency: 'PHP', symbol: '₱', ppp: 19.2632, exch: 55.6304, region: 'East Asia & Pacific' },
      { code: 'PL', name: 'Poland', currency: 'PLN', symbol: 'zł', ppp: 1.9205, exch: 4.2037, region: 'Europe & Central Asia' },
      { code: 'PT', name: 'Portugal', currency: 'EUR', symbol: '€', ppp: 0.5132, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'PR', name: 'Puerto Rico (US)', currency: 'USD', symbol: '$', ppp: 0.7778, exch: 1, region: 'Latin America & Caribbean' },
      { code: 'QA', name: 'Qatar', currency: 'QAR', symbol: '﷼', ppp: 2.3021, exch: 3.64, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'RO', name: 'Romania', currency: 'RON', symbol: 'lei', ppp: 1.815, exch: 4.5743, region: 'Europe & Central Asia' },
      { code: 'RU', name: 'Russia', currency: 'RUB', symbol: '₽', ppp: 27.2391, exch: 85.162, region: 'Europe & Central Asia' },
      { code: 'RW', name: 'Rwanda', currency: 'RWF', symbol: 'FRw', ppp: 350.4863, exch: 1160.0987, region: 'Sub-Saharan Africa' },
      { code: 'KN', name: 'Saint Kitts and Nevis', currency: 'XCD', symbol: '$', ppp: 1.7939, exch: 2.7, region: 'Latin America & Caribbean' },
      { code: 'LC', name: 'Saint Lucia', currency: 'XCD', symbol: '$', ppp: 1.409, exch: 2.7, region: 'Latin America & Caribbean' },
      { code: 'VC', name: 'Saint Vincent and the Grenadines', currency: 'XCD', symbol: '$', ppp: 1.4416, exch: 2.7, region: 'Latin America & Caribbean' },
      { code: 'WS', name: 'Samoa', currency: 'WST', symbol: 'WS$', ppp: 1.6069, exch: 2.7384, region: 'East Asia & Pacific' },
      { code: 'SM', name: 'San Marino', currency: 'EUR', symbol: '€', ppp: 0.7032, exch: 0.9247, region: 'Europe & Central Asia' },
      { code: 'ST', name: 'Sao Tome and Principe', currency: 'STN', symbol: 'Db', ppp: 11.1012, exch: 22.6584, region: 'Sub-Saharan Africa' },
      { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', symbol: '﷼', ppp: 1.8946, exch: 3.75, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'SN', name: 'Senegal', currency: 'XOF', symbol: 'CFA', ppp: 215.5837, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'RS', name: 'Serbia', currency: 'RSD', symbol: 'дин.', ppp: 44.7115, exch: 108.4027, region: 'Europe & Central Asia' },
      { code: 'SC', name: 'Seychelles', currency: 'SCR', symbol: '₨', ppp: 8.0555, exch: 14.0181, region: 'Sub-Saharan Africa' },
      { code: 'SL', name: 'Sierra Leone', currency: 'SLL', symbol: 'Le', ppp: 4.7965, exch: 21.3049, region: 'Sub-Saharan Africa' },
      { code: 'SG', name: 'Singapore', currency: 'SGD', symbol: 'S$', ppp: 0.7976, exch: 1.3428, region: 'East Asia & Pacific' },
      { code: 'SX', name: 'Sint Maarten (Dutch part)', currency: 'ANG', symbol: 'ƒ', ppp: 1.3663, exch: 1.79, region: 'Latin America & Caribbean' },
      { code: 'SK', name: 'Slovakia', currency: 'EUR', symbol: '€', ppp: 0.4963, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'SI', name: 'Slovenia', currency: 'EUR', symbol: '€', ppp: 0.5379, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'SB', name: 'Solomon Islands', currency: 'SBD', symbol: 'SI$', ppp: 6.0727, exch: 8.3756, region: 'East Asia & Pacific' },
      { code: 'SO', name: 'Somalia', currency: 'SOS', symbol: 'Sh', ppp: 10446.3228, exch: 23097.9873, region: 'Sub-Saharan Africa' },
      { code: 'ZA', name: 'South Africa', currency: 'ZAR', symbol: 'R', ppp: 7.3247, exch: 18.4502, region: 'Sub-Saharan Africa' },
      { code: 'KR', name: 'South Korea', currency: 'KRW', symbol: '₩', ppp: 811.048, exch: 1305.6625, region: 'East Asia & Pacific' },
      { code: 'SS', name: 'South Sudan', currency: 'SSP', symbol: '£', ppp: 126.743, exch: 930.3314, region: 'Sub-Saharan Africa' },
      { code: 'ES', name: 'Spain', currency: 'EUR', symbol: '€', ppp: 0.5565, exch: 0.9248, region: 'Europe & Central Asia' },
      { code: 'LK', name: 'Sri Lanka', currency: 'LKR', symbol: 'Rs', ppp: 86.0744, exch: 327.5065, region: 'South Asia' },
      { code: 'SD', name: 'Sudan', currency: 'SDG', symbol: '£', ppp: 217.2435, exch: 546.7589, region: 'Sub-Saharan Africa' },
      { code: 'SR', name: 'Suriname', currency: 'SRD', symbol: '$', ppp: 9.6198, exch: 36.7759, region: 'Latin America & Caribbean' },
      { code: 'SE', name: 'Sweden', currency: 'SEK', symbol: 'kr', ppp: 8.5166, exch: 10.6102, region: 'Europe & Central Asia' },
      { code: 'CH', name: 'Switzerland', currency: 'CHF', symbol: 'CHF', ppp: 0.999, exch: 0.8985, region: 'Europe & Central Asia' },
      { code: 'SY', name: 'Syria', currency: 'SYP', symbol: '£', ppp: 1757.5207, exch: 2505.7469, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'TJ', name: 'Tajikistan', currency: 'TJS', symbol: 'TJS', ppp: 2.5748, exch: 10.8445, region: 'Europe & Central Asia' },
      { code: 'TZ', name: 'Tanzania', currency: 'TZS', symbol: 'TSh', ppp: 725.8523, exch: 2383.0426, region: 'Sub-Saharan Africa' },
      { code: 'TH', name: 'Thailand', currency: 'THB', symbol: '฿', ppp: 10.6468, exch: 34.8022, region: 'East Asia & Pacific' },
      { code: 'TL', name: 'Timor-Leste', currency: 'USD', symbol: '$', ppp: 0.3126, exch: 1, region: 'East Asia & Pacific' },
      { code: 'TG', name: 'Togo', currency: 'XOF', symbol: 'CFA', ppp: 202.8705, exch: 606.5698, region: 'Sub-Saharan Africa' },
      { code: 'TO', name: 'Tonga', currency: 'TOP', symbol: 'T$', ppp: 1.7106, exch: 2.3637, region: 'East Asia & Pacific' },
      { code: 'TT', name: 'Trinidad and Tobago', currency: 'TTD', symbol: 'TT$', ppp: 3.5695, exch: 6.7503, region: 'Latin America & Caribbean' },
      { code: 'TN', name: 'Tunisia', currency: 'TND', symbol: 'd.t', ppp: 0.8741, exch: 3.1062, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'TR', name: 'Turkey', currency: 'TRY', symbol: '₺', ppp: 7.3503, exch: 23.7386, region: 'Europe & Central Asia' },
      { code: 'TC', name: 'Turks and Caicos Islands', currency: 'USD', symbol: '$', ppp: 1.0038, exch: 1, region: 'Latin America & Caribbean' },
      { code: 'UG', name: 'Uganda', currency: 'UGX', symbol: 'USh', ppp: 1214.1971, exch: 3726.1405, region: 'Sub-Saharan Africa' },
      { code: 'UA', name: 'Ukraine', currency: 'UAH', symbol: '₴', ppp: 10.6409, exch: 36.5738, region: 'Europe & Central Asia' },
      { code: 'AE', name: 'United Arab Emirates', currency: 'AED', symbol: 'د.إ', ppp: 2.3485, exch: 3.6725, region: 'Middle East, North Africa, Afghanistan & Pakistan' },
      { code: 'GB', name: 'United Kingdom', currency: 'GBP', symbol: '£', ppp: 0.6607, exch: 0.8045, region: 'Europe & Central Asia' },
      { code: 'US', name: 'United States', currency: 'USD', symbol: '$', ppp: 1, exch: 1, region: 'North America' },
      { code: 'UY', name: 'Uruguay', currency: 'UYU', symbol: '$U', ppp: 25.9263, exch: 38.8239, region: 'Latin America & Caribbean' },
      { code: 'UZ', name: 'Uzbekistan', currency: 'UZS', symbol: 'so\'m', ppp: 3041.7129, exch: 11734.8334, region: 'Europe & Central Asia' },
      { code: 'VU', name: 'Vanuatu', currency: 'VUV', symbol: 'VT', ppp: 116.2679, exch: 119.1125, region: 'East Asia & Pacific' },
      { code: 'VN', name: 'Vietnam', currency: 'VND', symbol: '₫', ppp: 6840.6117, exch: 23787.3192, region: 'East Asia & Pacific' },
      { code: 'VI', name: 'Virgin Islands (U.S.)', currency: 'USD', symbol: '$', ppp: 0.8901, exch: 1, region: 'Latin America & Caribbean' },
      { code: 'ZM', name: 'Zambia', currency: 'ZMW', symbol: 'ZK', ppp: 6.5972, exch: 20.212, region: 'Sub-Saharan Africa' },
      { code: 'ZW', name: 'Zimbabwe', currency: 'ZWG', symbol: 'ZWG', ppp: 0.7139, exch: 3509.1722, region: 'Sub-Saharan Africa' },
    ];

    const mvpCountries = countries.filter((c) => MVP_COUNTRY_CODES.has(c.code));

    for (const c of mvpCountries) {
      // upsert
      await runAsync(
        `INSERT OR REPLACE INTO countries (country_code, country_name, currency_code, currency_symbol, ppp_index, exchange_rate, region, updated_at) 
         VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`,
        [c.code, c.name, c.currency, c.symbol, c.ppp, c.exch, c.region]
      );
    }

    // Items: a categorized travel-basket checklist (group -> subgroup -> item).
    // pricing_model 'unit' = priced per instance x quantity. 'percentage' =
    // a rate (tipping, card/ATM fees, currency markup) applied to the
    // unit-priced subtotal instead of having its own per-unit price.
    await runAsync(`DELETE FROM prices`);
    await runAsync(`DELETE FROM items`);

    const items = [
      { name: 'Breakfast pastry or snack (1 item)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Casual sit-down meal (1 person)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Fast food combo meal (1 person)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Fine-dining meal (1 person, no drinks)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Bottled water (1.5L)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Coffee or tea (1 cup)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Local beer or glass of wine (1 drink)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Basic groceries (1 week, 1 person)', category: 'Food & drink', group: 'Daily essentials', model: 'unit' },
      { name: 'Restaurant tipping norm (% of bill)', category: 'Food & drink', group: 'Daily essentials', model: 'percentage' },
      { name: 'Public transit (1 ride)', category: 'Getting around', group: 'Daily essentials', model: 'unit' },
      { name: 'Day transit pass (1 day, unlimited rides)', category: 'Getting around', group: 'Daily essentials', model: 'unit' },
      { name: 'Taxi or rideshare (short ride, ~3km)', category: 'Getting around', group: 'Daily essentials', model: 'unit' },
      { name: 'Bike or scooter rental (1 day)', category: 'Getting around', group: 'Daily essentials', model: 'unit' },
      { name: 'Car rental with fuel (1 day)', category: 'Getting around', group: 'Daily essentials', model: 'unit' },
      { name: 'Parking (1 day)', category: 'Getting around', group: 'Daily essentials', model: 'unit' },
      { name: 'Road toll (1 pass-through)', category: 'Getting around', group: 'Daily essentials', model: 'unit' },
      { name: 'Local SIM card (one-time, no data)', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'Mobile data plan — 1GB', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'Mobile data plan — 5GB', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'Mobile data plan — 10GB', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'Mobile data plan — 20GB', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'Mobile data plan — Unlimited (1 day)', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'Portable wifi or hotspot rental (1 day)', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'International roaming add-on (1 day)', category: 'Staying connected', group: 'Daily essentials', model: 'unit' },
      { name: 'Hostel dorm bed (1 night)', category: 'Stay', group: 'Trip-level costs', model: 'unit' },
      { name: 'Budget hotel or guesthouse room (1 night)', category: 'Stay', group: 'Trip-level costs', model: 'unit' },
      { name: 'Mid-range hotel room (1 night)', category: 'Stay', group: 'Trip-level costs', model: 'unit' },
      { name: 'Boutique or luxury hotel room (1 night)', category: 'Stay', group: 'Trip-level costs', model: 'unit' },
      { name: 'Private Airbnb or vacation rental (1 night)', category: 'Stay', group: 'Trip-level costs', model: 'unit' },
      { name: 'Typical refundable deposit (hotel or rental)', category: 'Stay', group: 'Trip-level costs', model: 'unit' },
      { name: 'Intercity train ticket (one-way, standard class)', category: 'Getting between cities', group: 'Trip-level costs', model: 'unit' },
      { name: 'Long-distance bus ticket (one-way)', category: 'Getting between cities', group: 'Trip-level costs', model: 'unit' },
      { name: 'Domestic flight (one-way, economy)', category: 'Getting between cities', group: 'Trip-level costs', model: 'unit' },
      { name: 'Airport transfer (one-way)', category: 'Getting between cities', group: 'Trip-level costs', model: 'unit' },
      { name: 'Multi-day rail pass (e.g. 3-day unlimited)', category: 'Getting between cities', group: 'Trip-level costs', model: 'unit' },
      { name: 'International round-trip flight (estimated, economy)', category: 'Getting between cities', group: 'Trip-level costs', model: 'unit' },
      { name: 'Visa fee (single entry, per traveler)', category: 'Documents & insurance', group: 'Trip-level costs', model: 'unit' },
      { name: 'Travel insurance (per week of coverage)', category: 'Documents & insurance', group: 'Trip-level costs', model: 'unit' },
      { name: 'Vaccination or health certificate (one-time)', category: 'Documents & insurance', group: 'Trip-level costs', model: 'unit' },
      { name: 'Passport photos or printing (one set)', category: 'Documents & insurance', group: 'Trip-level costs', model: 'unit' },
      { name: 'Massage or spa treatment (1 hour)', category: 'Personal care', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Haircut (basic, 1 visit)', category: 'Personal care', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Toiletries restock (per trip)', category: 'Personal care', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Laundry service (1 load)', category: 'Personal care', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Gym day pass (1 day)', category: 'Personal care', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Museum or attraction entry (1 person)', category: 'Things to do', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Guided tour or day trip (1 person)', category: 'Things to do', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Adventure activity (1 person, e.g. diving or rafting)', category: 'Things to do', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Nightlife or club entry (1 person cover charge)', category: 'Things to do', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Concert or event ticket (1 ticket)', category: 'Things to do', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'National park entry (1 person)', category: 'Things to do', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Souvenir (1 typical item)', category: 'Shopping', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Basic clothing item (e.g. 1 T-shirt)', category: 'Shopping', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'Duty-free item (e.g. spirits or perfume)', category: 'Shopping', group: 'Lifestyle & discretionary', model: 'unit' },
      { name: 'ATM withdrawal fee (% per withdrawal)', category: 'Easy-to-forget hidden costs', group: 'Easy-to-forget hidden costs', model: 'percentage' },
      { name: 'Foreign transaction fee (% per card purchase)', category: 'Easy-to-forget hidden costs', group: 'Easy-to-forget hidden costs', model: 'percentage' },
      { name: 'Currency exchange markup (% vs mid-market rate)', category: 'Easy-to-forget hidden costs', group: 'Easy-to-forget hidden costs', model: 'percentage' },
      { name: 'General tipping norm (% of spending)', category: 'Easy-to-forget hidden costs', group: 'Easy-to-forget hidden costs', model: 'percentage' },
      { name: 'Departure or airport exit tax (per traveler)', category: 'Easy-to-forget hidden costs', group: 'Easy-to-forget hidden costs', model: 'unit' },
      { name: 'Checked baggage fee (1 bag, one-way)', category: 'Easy-to-forget hidden costs', group: 'Easy-to-forget hidden costs', model: 'unit' },
      { name: 'Emergency doctor visit (1 visit)', category: 'Easy-to-forget hidden costs', group: 'Easy-to-forget hidden costs', model: 'unit' },
    ];

    const mvpItems = items.filter((it) => MVP_ITEM_NAMES.has(it.name));

    for (const it of mvpItems) {
      await runAsync(
        `INSERT INTO items (name, category, group_name, pricing_model, description, created_at) VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`,
        [it.name, it.category, it.group, it.model, null]
      );
    }

    // Fetch item ids
    const itemRows = await new Promise((resolve, reject) => db.all(`SELECT id, name FROM items`, (err, rows) => err ? reject(err) : resolve(rows)));
    const itemsMap = {};
    for (const r of itemRows) itemsMap[r.name] = r.id;

    // Fetch country ids
    const countryRows = await new Promise((resolve, reject) => db.all(`SELECT id, country_code FROM countries`, (err, rows) => err ? reject(err) : resolve(rows)));
    const countryMap = {};
    for (const r of countryRows) countryMap[r.country_code] = r.id;

    // Anchor prices/rates for US, India, and the UK; every other country is
    // filled in automatically via the PPP-scaled (or rate passthrough, for
    // percentage items) fallback already used by the trip planner / converter.
    const prices = [
      { item: 'Breakfast pastry or snack (1 item)', country: 'US', price: 4 },
      { item: 'Breakfast pastry or snack (1 item)', country: 'IN', price: 40 },
      { item: 'Breakfast pastry or snack (1 item)', country: 'GB', price: 3 },
      { item: 'Casual sit-down meal (1 person)', country: 'US', price: 18 },
      { item: 'Casual sit-down meal (1 person)', country: 'IN', price: 300 },
      { item: 'Casual sit-down meal (1 person)', country: 'GB', price: 14 },
      { item: 'Fast food combo meal (1 person)', country: 'US', price: 9 },
      { item: 'Fast food combo meal (1 person)', country: 'IN', price: 250 },
      { item: 'Fast food combo meal (1 person)', country: 'GB', price: 7 },
      { item: 'Fine-dining meal (1 person, no drinks)', country: 'US', price: 80 },
      { item: 'Fine-dining meal (1 person, no drinks)', country: 'IN', price: 2000 },
      { item: 'Fine-dining meal (1 person, no drinks)', country: 'GB', price: 65 },
      { item: 'Bottled water (1.5L)', country: 'US', price: 1.5 },
      { item: 'Bottled water (1.5L)', country: 'IN', price: 20 },
      { item: 'Bottled water (1.5L)', country: 'GB', price: 1 },
      { item: 'Coffee or tea (1 cup)', country: 'US', price: 4.5 },
      { item: 'Coffee or tea (1 cup)', country: 'IN', price: 50 },
      { item: 'Coffee or tea (1 cup)', country: 'GB', price: 3 },
      { item: 'Local beer or glass of wine (1 drink)', country: 'US', price: 6 },
      { item: 'Local beer or glass of wine (1 drink)', country: 'IN', price: 150 },
      { item: 'Local beer or glass of wine (1 drink)', country: 'GB', price: 4.5 },
      { item: 'Basic groceries (1 week, 1 person)', country: 'US', price: 35 },
      { item: 'Basic groceries (1 week, 1 person)', country: 'IN', price: 600 },
      { item: 'Basic groceries (1 week, 1 person)', country: 'GB', price: 28 },
      { item: 'Restaurant tipping norm (% of bill)', country: 'US', price: 18 },
      { item: 'Restaurant tipping norm (% of bill)', country: 'IN', price: 5 },
      { item: 'Restaurant tipping norm (% of bill)', country: 'GB', price: 10 },
      { item: 'Public transit (1 ride)', country: 'US', price: 2.75 },
      { item: 'Public transit (1 ride)', country: 'IN', price: 20 },
      { item: 'Public transit (1 ride)', country: 'GB', price: 2.8 },
      { item: 'Day transit pass (1 day, unlimited rides)', country: 'US', price: 12 },
      { item: 'Day transit pass (1 day, unlimited rides)', country: 'IN', price: 150 },
      { item: 'Day transit pass (1 day, unlimited rides)', country: 'GB', price: 15 },
      { item: 'Taxi or rideshare (short ride, ~3km)', country: 'US', price: 15 },
      { item: 'Taxi or rideshare (short ride, ~3km)', country: 'IN', price: 100 },
      { item: 'Taxi or rideshare (short ride, ~3km)', country: 'GB', price: 6 },
      { item: 'Bike or scooter rental (1 day)', country: 'US', price: 20 },
      { item: 'Bike or scooter rental (1 day)', country: 'IN', price: 300 },
      { item: 'Bike or scooter rental (1 day)', country: 'GB', price: 15 },
      { item: 'Car rental with fuel (1 day)', country: 'US', price: 70 },
      { item: 'Car rental with fuel (1 day)', country: 'IN', price: 2500 },
      { item: 'Car rental with fuel (1 day)', country: 'GB', price: 55 },
      { item: 'Parking (1 day)', country: 'US', price: 5 },
      { item: 'Parking (1 day)', country: 'IN', price: 30 },
      { item: 'Parking (1 day)', country: 'GB', price: 4 },
      { item: 'Road toll (1 pass-through)', country: 'US', price: 6 },
      { item: 'Road toll (1 pass-through)', country: 'IN', price: 60 },
      { item: 'Road toll (1 pass-through)', country: 'GB', price: 3 },
      { item: 'Local SIM card (one-time, no data)', country: 'US', price: 10 },
      { item: 'Local SIM card (one-time, no data)', country: 'IN', price: 50 },
      { item: 'Local SIM card (one-time, no data)', country: 'GB', price: 5 },
      { item: 'Mobile data plan — 1GB', country: 'US', price: 5 },
      { item: 'Mobile data plan — 1GB', country: 'IN', price: 19 },
      { item: 'Mobile data plan — 1GB', country: 'GB', price: 3 },
      { item: 'Mobile data plan — 5GB', country: 'US', price: 15 },
      { item: 'Mobile data plan — 5GB', country: 'IN', price: 100 },
      { item: 'Mobile data plan — 5GB', country: 'GB', price: 8 },
      { item: 'Mobile data plan — 10GB', country: 'US', price: 30 },
      { item: 'Mobile data plan — 10GB', country: 'IN', price: 300 },
      { item: 'Mobile data plan — 10GB', country: 'GB', price: 15 },
      { item: 'Mobile data plan — 20GB', country: 'US', price: 50 },
      { item: 'Mobile data plan — 20GB', country: 'IN', price: 500 },
      { item: 'Mobile data plan — 20GB', country: 'GB', price: 25 },
      { item: 'Mobile data plan — Unlimited (1 day)', country: 'US', price: 10 },
      { item: 'Mobile data plan — Unlimited (1 day)', country: 'IN', price: 50 },
      { item: 'Mobile data plan — Unlimited (1 day)', country: 'GB', price: 5 },
      { item: 'Portable wifi or hotspot rental (1 day)', country: 'US', price: 12 },
      { item: 'Portable wifi or hotspot rental (1 day)', country: 'IN', price: 200 },
      { item: 'Portable wifi or hotspot rental (1 day)', country: 'GB', price: 8 },
      { item: 'International roaming add-on (1 day)', country: 'US', price: 10 },
      { item: 'International roaming add-on (1 day)', country: 'IN', price: 500 },
      { item: 'International roaming add-on (1 day)', country: 'GB', price: 6 },
      { item: 'Hostel dorm bed (1 night)', country: 'US', price: 35 },
      { item: 'Hostel dorm bed (1 night)', country: 'IN', price: 500 },
      { item: 'Hostel dorm bed (1 night)', country: 'GB', price: 25 },
      { item: 'Budget hotel or guesthouse room (1 night)', country: 'US', price: 70 },
      { item: 'Budget hotel or guesthouse room (1 night)', country: 'IN', price: 1000 },
      { item: 'Budget hotel or guesthouse room (1 night)', country: 'GB', price: 55 },
      { item: 'Mid-range hotel room (1 night)', country: 'US', price: 130 },
      { item: 'Mid-range hotel room (1 night)', country: 'IN', price: 2500 },
      { item: 'Mid-range hotel room (1 night)', country: 'GB', price: 100 },
      { item: 'Boutique or luxury hotel room (1 night)', country: 'US', price: 300 },
      { item: 'Boutique or luxury hotel room (1 night)', country: 'IN', price: 8000 },
      { item: 'Boutique or luxury hotel room (1 night)', country: 'GB', price: 250 },
      { item: 'Private Airbnb or vacation rental (1 night)', country: 'US', price: 150 },
      { item: 'Private Airbnb or vacation rental (1 night)', country: 'IN', price: 3000 },
      { item: 'Private Airbnb or vacation rental (1 night)', country: 'GB', price: 110 },
      { item: 'Typical refundable deposit (hotel or rental)', country: 'US', price: 200 },
      { item: 'Typical refundable deposit (hotel or rental)', country: 'IN', price: 5000 },
      { item: 'Typical refundable deposit (hotel or rental)', country: 'GB', price: 150 },
      { item: 'Intercity train ticket (one-way, standard class)', country: 'US', price: 40 },
      { item: 'Intercity train ticket (one-way, standard class)', country: 'IN', price: 500 },
      { item: 'Intercity train ticket (one-way, standard class)', country: 'GB', price: 35 },
      { item: 'Long-distance bus ticket (one-way)', country: 'US', price: 25 },
      { item: 'Long-distance bus ticket (one-way)', country: 'IN', price: 300 },
      { item: 'Long-distance bus ticket (one-way)', country: 'GB', price: 20 },
      { item: 'Domestic flight (one-way, economy)', country: 'US', price: 150 },
      { item: 'Domestic flight (one-way, economy)', country: 'IN', price: 5000 },
      { item: 'Domestic flight (one-way, economy)', country: 'GB', price: 90 },
      { item: 'Airport transfer (one-way)', country: 'US', price: 50 },
      { item: 'Airport transfer (one-way)', country: 'IN', price: 800 },
      { item: 'Airport transfer (one-way)', country: 'GB', price: 60 },

      { item: 'Multi-day rail pass (e.g. 3-day unlimited)', country: 'US', price: 120 },
      { item: 'Multi-day rail pass (e.g. 3-day unlimited)', country: 'IN', price: 1500 },
      { item: 'Multi-day rail pass (e.g. 3-day unlimited)', country: 'GB', price: 150 },
      { item: 'International round-trip flight (estimated, economy)', country: 'US', price: 700 },
      { item: 'International round-trip flight (estimated, economy)', country: 'IN', price: 45000 },
      { item: 'International round-trip flight (estimated, economy)', country: 'GB', price: 450 },
      { item: 'Visa fee (single entry, per traveler)', country: 'US', price: 185 },
      { item: 'Visa fee (single entry, per traveler)', country: 'IN', price: 80 },
      { item: 'Visa fee (single entry, per traveler)', country: 'GB', price: 100 },
      { item: 'Travel insurance (per week of coverage)', country: 'US', price: 45 },
      { item: 'Travel insurance (per week of coverage)', country: 'IN', price: 1500 },
      { item: 'Travel insurance (per week of coverage)', country: 'GB', price: 35 },
      { item: 'Vaccination or health certificate (one-time)', country: 'US', price: 75 },
      { item: 'Vaccination or health certificate (one-time)', country: 'IN', price: 1000 },
      { item: 'Vaccination or health certificate (one-time)', country: 'GB', price: 50 },
      { item: 'Passport photos or printing (one set)', country: 'US', price: 15 },
      { item: 'Passport photos or printing (one set)', country: 'IN', price: 150 },
      { item: 'Passport photos or printing (one set)', country: 'GB', price: 8 },
      { item: 'Massage or spa treatment (1 hour)', country: 'US', price: 60 },
      { item: 'Massage or spa treatment (1 hour)', country: 'IN', price: 300 },
      { item: 'Massage or spa treatment (1 hour)', country: 'GB', price: 40 },
      { item: 'Haircut (basic, 1 visit)', country: 'US', price: 30 },
      { item: 'Haircut (basic, 1 visit)', country: 'IN', price: 150 },
      { item: 'Haircut (basic, 1 visit)', country: 'GB', price: 20 },
      { item: 'Toiletries restock (per trip)', country: 'US', price: 15 },
      { item: 'Toiletries restock (per trip)', country: 'IN', price: 200 },
      { item: 'Toiletries restock (per trip)', country: 'GB', price: 10 },
      { item: 'Laundry service (1 load)', country: 'US', price: 10 },
      { item: 'Laundry service (1 load)', country: 'IN', price: 150 },
      { item: 'Laundry service (1 load)', country: 'GB', price: 8 },
      { item: 'Gym day pass (1 day)', country: 'US', price: 20 },
      { item: 'Gym day pass (1 day)', country: 'IN', price: 300 },
      { item: 'Gym day pass (1 day)', country: 'GB', price: 12 },
      { item: 'Museum or attraction entry (1 person)', country: 'US', price: 20 },
      { item: 'Museum or attraction entry (1 person)', country: 'IN', price: 500 },
      { item: 'Museum or attraction entry (1 person)', country: 'GB', price: 18 },
      { item: 'Guided tour or day trip (1 person)', country: 'US', price: 75 },
      { item: 'Guided tour or day trip (1 person)', country: 'IN', price: 2000 },
      { item: 'Guided tour or day trip (1 person)', country: 'GB', price: 60 },
      { item: 'Adventure activity (1 person, e.g. diving or rafting)', country: 'US', price: 120 },
      { item: 'Adventure activity (1 person, e.g. diving or rafting)', country: 'IN', price: 3000 },
      { item: 'Adventure activity (1 person, e.g. diving or rafting)', country: 'GB', price: 90 },
      { item: 'Nightlife or club entry (1 person cover charge)', country: 'US', price: 25 },
      { item: 'Nightlife or club entry (1 person cover charge)', country: 'IN', price: 1000 },
      { item: 'Nightlife or club entry (1 person cover charge)', country: 'GB', price: 20 },
      { item: 'Concert or event ticket (1 ticket)', country: 'US', price: 75 },
      { item: 'Concert or event ticket (1 ticket)', country: 'IN', price: 1500 },
      { item: 'Concert or event ticket (1 ticket)', country: 'GB', price: 60 },
      { item: 'National park entry (1 person)', country: 'US', price: 30 },
      { item: 'National park entry (1 person)', country: 'IN', price: 500 },
      { item: 'National park entry (1 person)', country: 'GB', price: 25 },
      { item: 'Souvenir (1 typical item)', country: 'US', price: 15 },
      { item: 'Souvenir (1 typical item)', country: 'IN', price: 400 },
      { item: 'Souvenir (1 typical item)', country: 'GB', price: 12 },
      { item: 'Basic clothing item (e.g. 1 T-shirt)', country: 'US', price: 20 },
      { item: 'Basic clothing item (e.g. 1 T-shirt)', country: 'IN', price: 500 },
      { item: 'Basic clothing item (e.g. 1 T-shirt)', country: 'GB', price: 15 },
      { item: 'Duty-free item (e.g. spirits or perfume)', country: 'US', price: 35 },
      { item: 'Duty-free item (e.g. spirits or perfume)', country: 'IN', price: 2500 },
      { item: 'Duty-free item (e.g. spirits or perfume)', country: 'GB', price: 25 },
      { item: 'ATM withdrawal fee (% per withdrawal)', country: 'US', price: 3 },
      { item: 'ATM withdrawal fee (% per withdrawal)', country: 'IN', price: 2.5 },
      { item: 'ATM withdrawal fee (% per withdrawal)', country: 'GB', price: 2 },
      { item: 'Foreign transaction fee (% per card purchase)', country: 'US', price: 3 },
      { item: 'Foreign transaction fee (% per card purchase)', country: 'IN', price: 2 },
      { item: 'Foreign transaction fee (% per card purchase)', country: 'GB', price: 2.5 },
      { item: 'Currency exchange markup (% vs mid-market rate)', country: 'US', price: 4 },
      { item: 'Currency exchange markup (% vs mid-market rate)', country: 'IN', price: 3 },
      { item: 'Currency exchange markup (% vs mid-market rate)', country: 'GB', price: 3.5 },
      { item: 'General tipping norm (% of spending)', country: 'US', price: 18 },
      { item: 'General tipping norm (% of spending)', country: 'IN', price: 5 },
      { item: 'General tipping norm (% of spending)', country: 'GB', price: 10 },
      { item: 'Departure or airport exit tax (per traveler)', country: 'US', price: 0 },
      { item: 'Departure or airport exit tax (per traveler)', country: 'IN', price: 1000 },
      { item: 'Departure or airport exit tax (per traveler)', country: 'GB', price: 13 },
      { item: 'Checked baggage fee (1 bag, one-way)', country: 'US', price: 35 },
      { item: 'Checked baggage fee (1 bag, one-way)', country: 'IN', price: 1500 },
      { item: 'Checked baggage fee (1 bag, one-way)', country: 'GB', price: 25 },
      { item: 'Emergency doctor visit (1 visit)', country: 'US', price: 150 },
      { item: 'Emergency doctor visit (1 visit)', country: 'IN', price: 800 },
      { item: 'Emergency doctor visit (1 visit)', country: 'GB', price: 40 },
    ];

    for (const p of prices) {
      const itemId = itemsMap[p.item];
      const countryId = countryMap[p.country];
      if (!itemId || !countryId) continue;
      await runAsync(
        `INSERT OR REPLACE INTO prices (item_id, country_id, price, currency_code, source, last_updated) VALUES (?, ?, ?, ?, 'manual', CURRENT_TIMESTAMP)`,
        [itemId, countryId, p.price, countryRows.find(c => c.id === countryId)?.country_code || '']
      );
    }

    console.log('Seeding complete.');
    process.exit(0);
  } catch (err) {
    console.error('Seeding failed:', err);
    process.exit(1);
  }
}

seed();
